name: CI with Dependency Caching

on:
  workflow_dispatch:   # allows manual run
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Setup Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # 3️⃣ Cache dependencies
      - name: prime-cache-6b26132
        id: cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: cache-6b26132
          restore-keys: cache-6b26132

      # 4️⃣ Show cache hit/miss
      - name: Show cache result
        run: echo "Cache hit? ${{ steps.cache.outputs.cache-hit }}"

      # 5️⃣ Install Python dependencies
      - name: Install dependencies
        run: |
          pip install requests

      # 6️⃣ Step with your email
      - name: 24f3004473@ds.study.iitm.ac.in
        run: echo "Hello, GitHub Actions!"
